repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.71.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    #- id: terraform_validate
    - id: terraform_tflint
      args:
        - 'args=--deep'
        - 'args=--enable-rule=terraform_documented_variables'
    - id: terraform_tfsec
