name: Check Github IP Ranges

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: test
        uses: ExpediaGroup/github-helpers@revert-771-revert-770-revert-769-revert-768-node-24
        with:
          helper: set-commit-status
          sha: ${{ github.event.pull_request.head.sha }}
          context: Commit Status Test
          state: success
          description: set-commit-status is working!
