name: Publish Assets

on:
  release:
    types:
      - edited
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install
        run: bun i

      - name: Build
        run: bun run build

      - name: Inject Mozilla Cert Bundles
        run: curl https://curl.se/ca/cacert.pem -o build/public-certs.pem

      - name: Zip Lambda
        run: zip -r -qq proxy-lambda.zip build node_modules

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: proxy-lambda.zip
