name: Publish Assets

on:
  release:
    types:
      - edited
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Inject Mozilla Cert Bundles
        run: curl https://curl.se/ca/cacert.pem -o build/public-certs.pem

      - name: Zip Lambda
        run: zip -r -qq proxy-lambda.zip build node_modules

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: proxy-lambda.zip
