name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun i

      - name: Format
        run: bun run format-check

      - name: Type Check
        run: bun tsc

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          git-push: true
          output-file: USAGE.md

  terraform:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read .terraform-version
        run: echo TF_VERSION=`cat .terraform-version` >> $GITHUB_ENV

      - name: Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        uses: dflook/terraform-validate@v1

      - name: Terraform FMT
        uses: dflook/terraform-fmt@v1

      - name: Terraform Lint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
