name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm ci

      - name: Format
        run: npm run format-check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-push: true
          output-file: USAGE.md

  terraform:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read .terraform-version
        run: echo TF_VERSION=`cat .terraform-version` >> $GITHUB_ENV

      - name: Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        uses: dflook/terraform-validate@v1

      - name: Terraform FMT
        uses: dflook/terraform-fmt@v1

      - name: Terraform Lint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
